spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whatSeoul?serverTimezone=Asia/Seoul
    username: root
    password: tnqls9004

  devtools:
    restart:
      enabled: true

  jpa:
    database: mysql
    #show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: update

# 서울 공공데이터 OPEN API
seoul:
  open:
    api:
      url: http://openapi.seoul.go.kr:8088/4e4f4d6774736f6f35385a6f416e49/xml/citydata/1/1
      key: 4e4f4d6774736f6f35385a6f416e49
server:
  port: 8080