spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whatseouldb?serverTimezone=Asia/Seoul
    username: root
    password: actor102933*

  devtools:
    restart:
      enabled: true

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: update
server:
  port: 8080