spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://whatseoul-server.c1cwae2csgaf.ap-northeast-2.rds.amazonaws.com:3306/whatseoulServer?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: whatseoul
    password: whatseoul99
  devtools:
    restart:
      enabled: true

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: update

server:
  port: 8080